In [1]:
import pandas as pd

<h1>Feature Engineering<h1/>


In [2]:
df = pd.read_csv('water_potability.csv')
df.head()


ph    Hardness        Solids  Chloramines     Sulfate  Conductivity  \
0       NaN  204.890455  20791.318981     7.300212  368.516441    564.308654   
1  3.716080  129.422921  18630.057858     6.635246         NaN    592.885359   
2  8.099124  224.236259  19909.541732     9.275884         NaN    418.606213   
3  8.316766  214.373394  22018.417441     8.059332  356.886136    363.266516   
4  9.092223  181.101509  17978.986339     6.546600  310.135738    398.410813   

   Organic_carbon  Trihalomethanes  Turbidity  Potability  
0       10.379783        86.990970   2.963135           0  
1       15.180013        56.329076   4.500656           0  
2       16.868637        66.420093   3.055934           0  
3       18.436524       100.341674   4.628771           0  
4       11.558279        31.997993   4.075075           0

In [3]:
df.tail()


ph    Hardness        Solids  Chloramines     Sulfate  \
3271  4.668102  193.681735  47580.991603     7.166639  359.948574   
3272  7.808856  193.553212  17329.802160     8.061362         NaN   
3273  9.419510  175.762646  33155.578218     7.350233         NaN   
3274  5.126763  230.603758  11983.869376     6.303357         NaN   
3275  7.874671  195.102299  17404.177061     7.509306         NaN   

      Conductivity  Organic_carbon  Trihalomethanes  Turbidity  Potability  
3271    526.424171       13.894419        66.687695   4.435821           1  
3272    392.449580       19.903225              NaN   2.798243           1  
3273    432.044783       11.039070        69.845400   3.298875           1  
3274    402.883113       11.168946        77.488213   4.708658           1  
3275    327.459760       16.140368        78.698446   2.309149           1

**Handle the null value**

In [4]:
df.isnull().sum()


ph                 491
Hardness             0
Solids               0
Chloramines          0
Sulfate            781
Conductivity         0
Organic_carbon       0
Trihalomethanes    162
Turbidity            0
Potability           0
dtype: int64

In [5]:
df.ph.fillna(df.ph.mean(), inplace=True)


In [6]:
df.Sulfate.fillna(df.Sulfate.mean(), inplace=True)


In [7]:
df.Trihalomethanes.fillna(df.Trihalomethanes.mean(), inplace=True)


In [8]:
df.head()


ph    Hardness        Solids  Chloramines     Sulfate  Conductivity  \
0  7.080795  204.890455  20791.318981     7.300212  368.516441    564.308654   
1  3.716080  129.422921  18630.057858     6.635246  333.775777    592.885359   
2  8.099124  224.236259  19909.541732     9.275884  333.775777    418.606213   
3  8.316766  214.373394  22018.417441     8.059332  356.886136    363.266516   
4  9.092223  181.101509  17978.986339     6.546600  310.135738    398.410813   

   Organic_carbon  Trihalomethanes  Turbidity  Potability  
0       10.379783        86.990970   2.963135           0  
1       15.180013        56.329076   4.500656           0  
2       16.868637        66.420093   3.055934           0  
3       18.436524       100.341674   4.628771           0  
4       11.558279        31.997993   4.075075           0

In [9]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3276 entries, 0 to 3275
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   ph               3276 non-null   float64
 1   Hardness         3276 non-null   float64
 2   Solids           3276 non-null   float64
 3   Chloramines      3276 non-null   float64
 4   Sulfate          3276 non-null   float64
 5   Conductivity     3276 non-null   float64
 6   Organic_carbon   3276 non-null   float64
 7   Trihalomethanes  3276 non-null   float64
 8   Turbidity        3276 non-null   float64
 9   Potability       3276 non-null   int64  
dtypes: float64(9), int64(1)
memory usage: 256.1 KB


In [10]:
df.describe()


ph     Hardness        Solids  Chloramines      Sulfate  \
count  3276.000000  3276.000000   3276.000000  3276.000000  3276.000000   
mean      7.080795   196.369496  22014.092526     7.122277   333.775777   
std       1.469956    32.879761   8768.570828     1.583085    36.142612   
min       0.000000    47.432000    320.942611     0.352000   129.000000   
25%       6.277673   176.850538  15666.690297     6.127421   317.094638   
50%       7.080795   196.967627  20927.833607     7.130299   333.775777   
75%       7.870050   216.667456  27332.762127     8.114887   350.385756   
max      14.000000   323.124000  61227.196008    13.127000   481.030642   

       Conductivity  Organic_carbon  Trihalomethanes    Turbidity   Potability  
count   3276.000000     3276.000000      3276.000000  3276.000000  3276.000000  
mean     426.205111       14.284970        66.396293     3.966786     0.390110  
std       80.824064        3.308162        15.769881     0.780382     0.487849  
min      181.483754        2.200000         0.738000     1.450000     0.000000  
25%      365.734414       12.065801        56.647656     3.439711     0.000000  
50%      421.884968       14.218338        66.396293     3.955028     0.000000  
75%      481.792304       16.557652        76.666609     4.500320     1.000000  
max      753.342620       28.300000       124.000000     6.739000     1.000000

In [11]:
df.groupby('Potability').sum()


ph       Hardness        Solids   Chloramines  \
Potability                                                            
0           14155.146761  393073.117785  4.351143e+07  14170.164778   
1            9041.536035  250233.351168  2.860674e+07   9162.413998   

                  Sulfate   Conductivity  Organic_carbon  Trihalomethanes  \
Potability                                                                  
0           668074.656250  852607.446223    28699.941889    132484.426367   
1           425374.787927  543640.496373    18097.620642     85029.829327   

              Turbidity  
Potability               
0           7923.667939  
1           5071.523554

**Now my data pretty good now proced to the machine learing part**

<h1>Machine Learing<h1/>

In [12]:
from sklearn.model_selection import train_test_split


In [13]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('Potability', axis='columns'), df.Potability, test_size=0.3, random_state=10)

**Now which algorithm is best for my dataset we use gribsearchcv algorithm**

In [14]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.neighbors import KNeighborsClassifier


In [15]:
from sklearn.model_selection import cross_val_score


In [16]:
model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params': {
            'C': [1, 10, 20],
            'kernel': ['rbf']
        }
    },
    'knn': {
        'model': KNeighborsClassifier(),
        'params': {
            'n_neighbors': [1, 5, 10, 15, 20, 30]
        }
    },
    'random_forest': {

        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [1, 10, 20, 30, 40, 50, 60, 70, 90, 100, 101, 120]
        },
    },
    'l_g': {
        'model': LogisticRegression(solver='liblinear', multi_class='auto'),
        'params': {
            'C': [1, 5, 10],
        }
    },
    'GussNB': {
        'model': GaussianNB(),
        'params': {}
    },
    'mul_NB': {
        'model': MultinomialNB(),
        'params': {}
    },
    'dtc': {
        'model': DecisionTreeClassifier(),
        'params': {
            'criterion': ['gini', 'entropy'],
            'splitter': ['best', 'random']
        }
    }
}


In [17]:
from sklearn.model_selection import GridSearchCV
scores = []

for model_names,mp in model_params.items():
    clf = GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
    clf.fit(df.drop('Potability',axis='columns'),df.Potability)
    scores.append({
        'model': model_names,
        'best_score': clf.best_score_,
        'best_params':clf.best_params_
    })
df2 = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df2


model  best_score                                best_params
0            svm    0.609890                  {'C': 1, 'kernel': 'rbf'}
1            knn    0.604096                        {'n_neighbors': 30}
2  random_forest    0.637682                       {'n_estimators': 40}
3            l_g    0.610195                                   {'C': 1}
4         GussNB    0.611417                                         {}
5         mul_NB    0.528084                                         {}
6            dtc    0.576016  {'criterion': 'gini', 'splitter': 'best'}

In [18]:
cross_val_score(RandomForestClassifier(n_estimators=10), X_train, y_train, cv=5)

array([0.63834423, 0.62091503, 0.63834423, 0.62882096, 0.62882096])

In [19]:
cross_val_score(RandomForestClassifier(n_estimators=30),X_train,y_train,cv=5)

array([0.64488017, 0.64052288, 0.64052288, 0.65065502, 0.62445415])

In [20]:
cross_val_score(RandomForestClassifier(n_estimators=50), X_train, y_train, cv=5)

array([0.64923747, 0.65359477, 0.66884532, 0.66593886, 0.64628821])

In [21]:
cross_val_score(RandomForestClassifier(n_estimators=60), X_train, y_train, cv=5)

array([0.64923747, 0.66013072, 0.7167756 , 0.68558952, 0.65065502])

In [22]:
cross_val_score(RandomForestClassifier(n_estimators=70), X_train, y_train, cv=5)

array([0.66013072, 0.64270153, 0.68191721, 0.66593886, 0.63755459])

In [23]:
cross_val_score(RandomForestClassifier(n_estimators=80), X_train, y_train, cv=5)

array([0.64270153, 0.66666667, 0.68409586, 0.66812227, 0.62663755])

In [24]:
cross_val_score(RandomForestClassifier(n_estimators=90), X_train, y_train, cv=5)


array([0.64270153, 0.65795207, 0.69716776, 0.66812227, 0.63537118])

In [25]:
cross_val_score(RandomForestClassifier(n_estimators=100), X_train, y_train, cv=5)


array([0.64488017, 0.65577342, 0.66666667, 0.68995633, 0.65938865])

In [26]:
cross_val_score(RandomForestClassifier(n_estimators=110), X_train, y_train, cv=5)

array([0.66013072, 0.65359477, 0.70152505, 0.67030568, 0.64847162])

**From above I get that randomforestclassifier give best score at n_estimators=90**

# Now dump into pickle file

In [27]:
import pickle
import numpy as np

array([0.65141612, 0.66230937, 0.708061  , 0.68777293, 0.65065502])

In [28]:
random_forest = RandomForestClassifier(n_estimators=90)
random_forest.fit(X_train,y_train)

RandomForestClassifier(n_estimators=90)

In [29]:
df.head()

ph    Hardness        Solids  Chloramines     Sulfate  Conductivity  \
0  7.080795  204.890455  20791.318981     7.300212  368.516441    564.308654   
1  3.716080  129.422921  18630.057858     6.635246  333.775777    592.885359   
2  8.099124  224.236259  19909.541732     9.275884  333.775777    418.606213   
3  8.316766  214.373394  22018.417441     8.059332  356.886136    363.266516   
4  9.092223  181.101509  17978.986339     6.546600  310.135738    398.410813   

   Organic_carbon  Trihalomethanes  Turbidity  Potability  
0       10.379783        86.990970   2.963135           0  
1       15.180013        56.329076   4.500656           0  
2       16.868637        66.420093   3.055934           0  
3       18.436524       100.341674   4.628771           0  
4       11.558279        31.997993   4.075075           0

In [30]:
# Correctly formatted input data
input_data = '5.324941855611651,280.08965491445105,35344.658047005905,13.043806107761025,180.20674636482346,392.42149580418476,10.50481954758385,55.084667854857926,4.427137925692965'

# Convert the input string into a NumPy array
input_values = [float(val) for val in input_data.split(',')]
input_data_as_numpy_array = np.asarray(input_values)

# Reshape the array
input_data_reshape = input_data_as_numpy_array.reshape(1, -1)

# Now you can make predictions
prediction = random_forest.predict(input_data_reshape)
print(prediction)

if prediction[0] == 1:
    print("The water is drinkable")
else:
    print("The water is not drinkable")

[1]
The water is drinkable


c:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [31]:
filename = 'trained_model.sav'
pickle.dump(random_forest,open(filename,'wb'))

In [32]:
load_model = pickle.load(open('trained_model.sav','rb'))

In [33]:
# Correctly formatted input data
# input_data = '5.324941855611651,280.08965491445105,35344.658047005905,13.043806107761025,180.20674636482346,392.42149580418476,10.50481954758385,55.084667854857926,4.427137925692965'

input_data = '90,0,0,0,0,0,0,0,0'

# Convert the input string into a NumPy array
input_values = [float(val) for val in input_data.split(',')]
input_data_as_numpy_array = np.asarray(input_values)

# Reshape the array
input_data_reshape = input_data_as_numpy_array.reshape(1, -1)

# Create a DataFrame with feature names (replace with your actual feature names)
# feature_names = ['ph', 'Hardness', 'Solids', 'Chloramines', 'Sulfate', 'Conductivity', 'Organic_carbon', 'Trihalomethanes', 'Turbidity']
# input_df = pd.DataFrame(input_data_reshape, columns=feature_names)

# Now you can make predictions
prediction = load_model.predict(input_data_reshape)
print(prediction)

if prediction[0] == 1:
    print("The water is drinkable")
else:
    print("The water is not drinkable")

[0]
The water is not drinkable


c:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [34]:
filename = 'final_model.pkl'
pickle.dump(random_forest,open(filename,'wb'))

In [35]:
load_model_fi = pickle.load(open('final_model.pkl','rb'))